version: '2'
services:
 jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  depends_on: 
    - sonar

 sonar:
  build: ./sonar
  ports:
    - "19000:9000"
  depends_on: 
    - db
 db:
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar